"""add_questionnaire_trust_center_integration_models

Revision ID: fa26c8ce9a1b
Revises: 0003
Create Date: 2026-05-26 18:05:17.139796
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "fa26c8ce9a1b"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("last_status", sa.String(length=50), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trust_center_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("document_type", sa.String(length=50), nullable=True),
        sa.Column("file_url", sa.String(length=1000), nullable=True),
        sa.Column("requires_nda", sa.Boolean(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("download_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trust_center_settings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("custom_domain", sa.String(length=255), nullable=True),
        sa.Column("page_title", sa.String(length=255), nullable=True),
        sa.Column("hero_headline", sa.String(length=500), nullable=True),
        sa.Column("hero_subtext", sa.Text(), nullable=True),
        sa.Column("brand_color", sa.String(length=7), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("favicon_url", sa.String(length=500), nullable=True),
        sa.Column("show_certifications", sa.Boolean(), nullable=True),
        sa.Column("show_controls", sa.Boolean(), nullable=True),
        sa.Column("show_policies", sa.Boolean(), nullable=True),
        sa.Column("show_ai_chatbot", sa.Boolean(), nullable=True),
        sa.Column("show_subscribe", sa.Boolean(), nullable=True),
        sa.Column("show_document_requests", sa.Boolean(), nullable=True),
        sa.Column("require_nda", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id"),
    )
    op.create_table(
        "trust_center_subscribers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("subscribed", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trust_center_visits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("visitor_ip", sa.String(length=45), nullable=True),
        sa.Column("page_viewed", sa.String(length=255), nullable=True),
        sa.Column("referrer", sa.String(length=500), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("chatbot_queries", sa.Integer(), nullable=True),
        sa.Column("document_downloads", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "compliance_tests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("integration_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("frameworks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("control_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trust_center_access_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("requester_email", sa.String(length=255), nullable=False),
        sa.Column("requester_name", sa.String(length=255), nullable=True),
        sa.Column("requester_company", sa.String(length=255), nullable=True),
        sa.Column("nda_accepted", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("approved_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["trust_center_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "test_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("test_id", sa.String(length=36), nullable=True),
        sa.Column("integration_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("resources_checked", sa.Integer(), nullable=True),
        sa.Column("resources_failed", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["compliance_tests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("answer_generations", sa.Column("questionnaire_id", sa.String(length=36), nullable=True))
    op.add_column("answer_generations", sa.Column("original_filename", sa.String(length=500), nullable=True))
    op.add_column("answer_generations", sa.Column("original_format", sa.String(length=20), nullable=True))
    op.add_column("answer_generations", sa.Column("engine_used", sa.String(length=50), nullable=True))
    op.create_foreign_key(None, "answer_generations", "questionnaires", ["questionnaire_id"], ["id"])
    op.add_column("answers", sa.Column("confidence_score", sa.Integer(), nullable=True))
    op.add_column("answers", sa.Column("assignee_id", sa.String(length=36), nullable=True))
    op.add_column("answers", sa.Column("order_index", sa.Integer(), nullable=True))
    op.add_column("answers", sa.Column("source", sa.String(length=50), nullable=True))
    op.create_foreign_key(None, "answers", "users", ["assignee_id"], ["id"])
    op.alter_column(
        "organizations",
        "brand_color",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=7),
        existing_nullable=True,
        existing_server_default=sa.text("'#0f766e'::character varying"),
    )
    op.alter_column(
        "organizations", "logo_url", existing_type=sa.TEXT(), type_=sa.String(length=500), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organizations", "logo_url", existing_type=sa.String(length=500), type_=sa.TEXT(), existing_nullable=True
    )
    op.alter_column(
        "organizations",
        "brand_color",
        existing_type=sa.String(length=7),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
        existing_server_default=sa.text("'#0f766e'::character varying"),
    )
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.drop_column("answers", "source")
    op.drop_column("answers", "order_index")
    op.drop_column("answers", "assignee_id")
    op.drop_column("answers", "confidence_score")
    op.drop_constraint(None, "answer_generations", type_="foreignkey")
    op.drop_column("answer_generations", "engine_used")
    op.drop_column("answer_generations", "original_format")
    op.drop_column("answer_generations", "original_filename")
    op.drop_column("answer_generations", "questionnaire_id")
    op.drop_table("test_results")
    op.drop_table("trust_center_access_requests")
    op.drop_table("compliance_tests")
    op.drop_table("trust_center_visits")
    op.drop_table("trust_center_subscribers")
    op.drop_table("trust_center_settings")
    op.drop_table("trust_center_documents")
    op.drop_table("integrations")
    # ### end Alembic commands ###
